Completed javascript-methods
K-Bowler/rc0122-code-solutions pull request #31
Opened 2022-02-02 19:31 UTC by K-Bowler

![javascript-methods](https://user-images.githubusercontent.com/43438792/152222353-bdd307ba-369e-4110-971d-44c60b95bcec.png)

2022-02-02 19:35 UTC, TimelikeClosure requested changes

2022-02-02 19:35 UTC, TimelikeClosure commented on javascript-methods/main.js
> +console.log('My name is', SayMyJName);
`toLocaleUpperCase` is not the same method as `toUpperCase`. Also, please use `camelCase` for your variable names: `PascalCase` should only be used for certain types of functions (which we'll discuss in detail in a couple weeks):

---

![image](https://user-images.githubusercontent.com/16143771/152224109-218c9e62-ca56-42da-8138-976490671860.png)

2022-02-02 20:38 UTC, TimelikeClosure requested changes

2022-02-02 20:38 UTC, TimelikeClosure commented on javascript-methods/main.js
> +console.log('My name is', SayMyName);
Please use `camelCase`, not `PascalCase`

2022-02-03 17:42 UTC, Zhiwutian approved these changes
👍🏼

2022-02-03 19:08 UTC, merged